name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: ./server

      - name: Type check
        run: npm run type-check
        working-directory: ./server

      - name: Run tests
        run: npm run test
        working-directory: ./server

      - name: Build
        run: npm run build
        working-directory: ./server
