name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Type check
        run: npx tsc --noEmit
        working-directory: ./client

      - name: Lint
        run: npm run lint
        working-directory: ./client

      - name: Run tests
        run: npm run test
        working-directory: ./client

      - name: Build
        run: npm run build
        working-directory: ./client
